In [11]:
import pandas as pd

In [12]:
df = pd.read_csv(r'..\dados\itunes_music_dataset.csv', sep=',')

In [13]:
# Qual é o número total de músicas no dataset?
print(f"O dataset contém {len(df)} músicas.")

# Quais são os tipos de dados de cada coluna?
df.dtypes

O dataset contém 4915 músicas.

track_id               int64
track_name            object
artist_name           object
collection_name       object
album_artist          object
genre                 object
rating                object
track_price          float64
collection_price     float64
release_date          object
track_time_millis      int64
country               object
currency              object
preview_url           object
artwork_url           object
dtype: object

In [14]:
# Verifique as colunas country e currency. Elas possuem mais de um valor ou o dataset é exclusivo de um mercado específico (ex: USA / USD)?
parametros = ['country', 'currency']
df[parametros].value_counts()

country  currency
USA      USD         4915
Name: count, dtype: int64

In [15]:
# Descubra quais colunas possuem valores nulos.
df.isnull().sum()

track_id                0
track_name              0
artist_name             2
collection_name         0
album_artist         3187
genre                   0
rating                  0
track_price           375
collection_price      376
release_date           48
track_time_millis       0
country                 0
currency                0
preview_url             1
artwork_url             0
dtype: int64

In [16]:
# Criando coluna do artista principal
df['main_artist'] = df['artist_name']

# Padronizando os feats
df['main_artist'] = df['main_artist'].str.replace(' feat. ', ' & ', case=False)
df['main_artist'] = df['main_artist'].str.replace(' ft. ', ' & ', case=False)
df['main_artist'] = df['main_artist'].str.replace(' feat ', ' & ', case=False)
df['main_artist'] = df['main_artist'].str.replace(',', ' & ')

# Separa pelo ' & '
df['main_artist'] = df['main_artist'].str.split(' & ').str[0]

# Limpa espaços em brancos
df['main_artist'] = df['main_artist'].str.strip()

In [17]:
# Ação: Preencha os preços nulos com o valor mediano do seu respectivo gênero musical. Exclua as linhas onde a data de lançamento (release_date) seja nula.
df['track_price'] = df.groupby('genre')['track_price'].transform(lambda x: x.fillna(x.median()))
df['collection_price'] = df.groupby('genre')['collection_price'].transform(lambda x: x.fillna(x.median()))
df = df.dropna(subset=['release_date'])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4867 entries, 0 to 4914
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   track_id           4867 non-null   int64
 1   track_name         4867 non-null   object
 2   artist_name        4865 non-null   object
 3   collection_name    4867 non-null   object
 4   album_artist       1706 non-null   object
 5   genre              4867 non-null   object
 6   rating             4867 non-null   object
 7   track_price        4866 non-null   float64
 8   collection_price   4866 non-null   float64
 9   release_date       4867 non-null   object
 10  track_time_millis  4867 non-null   int64
 11  country            4867 non-null   object
 12  currency           4867 non-null   object
 13  preview_url        4867 non-null   object
 14  artwork_url        4867 non-null   object
 15  main_artist        4865 non-null   object
dtypes: float64(2), int64(2), object(12)
memory usage: 646.4+ KB

In [19]:
# A coluna track_time_millis está em milissegundos, o que é péssimo para a leitura de negócios. Crie uma nova coluna chamada track_time_minutes convertendo esse valor para minutos.
df['track_time_minutes'] = round(df['track_time_millis'] / 60000, 2)

In [20]:
df.head()

,track_id,track_name,artist_name,collection_name,album_artist,genre,rating,track_price,collection_price,release_date,track_time_millis,country,currency,preview_url,artwork_url,main_artist,track_time_minutes
0,1624932774,POP!,NAYEON,IM NAYEON,NaN,Dance,Clean,1.29,6.99,2022-06-24T12:00:00Z,168107,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,NAYEON,2.80
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),NaN,Alternative,Clean,1.29,9.99,2013-03-22T07:00:00Z,202019,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,Vance Joy,3.37
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,The Chainsmokers,Dance,Clean,1.29,9.99,2017-02-22T08:00:00Z,247165,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,The Chainsmokers,4.12
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,NaN,Pop,Clean,1.29,1.29,2018-04-19T12:00:00Z,200187,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,Billie Eilish,3.34
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",NaN,Alternative,Clean,1.29,10.99,2018-10-17T07:00:00Z,196077,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,Billie Eilish,3.27

In [21]:
# Converta a coluna release_date para o formato de Data (Datetime) e extraia uma nova coluna chamada release_year.
df['release_date'] = pd.to_datetime(df['release_date'])
df['release_year'] = df['release_date'].dt.year

In [22]:
df.head()

,track_id,track_name,artist_name,collection_name,album_artist,genre,rating,track_price,collection_price,release_date,track_time_millis,country,currency,preview_url,artwork_url,main_artist,track_time_minutes,release_year
0,1624932774,POP!,NAYEON,IM NAYEON,NaN,Dance,Clean,1.29,6.99,2022-06-24 12:00:00+00:00,168107,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,NAYEON,2.80,2022
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),NaN,Alternative,Clean,1.29,9.99,2013-03-22 07:00:00+00:00,202019,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,Vance Joy,3.37,2013
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,The Chainsmokers,Dance,Clean,1.29,9.99,2017-02-22 08:00:00+00:00,247165,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,The Chainsmokers,4.12,2017
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,NaN,Pop,Clean,1.29,1.29,2018-04-19 12:00:00+00:00,200187,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,Billie Eilish,3.34,2018
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",NaN,Alternative,Clean,1.29,10.99,2018-10-17 07:00:00+00:00,196077,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,Billie Eilish,3.27,2018

In [23]:
# Quais são os 5 gêneros musicais mais comuns neste dataset?
top_5_genre = df['genre'].value_counts().head(5).index

In [24]:
# Qual é a duração média das músicas (track_time_minutes) para cada um desses 5 gêneros? (Ex: Músicas de Eletrônica são mais longas que as de Pop?)
df[df['genre'].isin(top_5_genre)].groupby('genre')['track_time_minutes'].mean().round(2)

genre
Bollywood      4.49
Hip-Hop/Rap    3.73
Pop            3.81
R&B/Soul       3.95
Rock           3.79
Name: track_time_minutes, dtype: float64

In [25]:
# Qual é o preço médio de uma música (track_price) e de um álbum (collection_price) geral?
parametros = ['track_price', 'collection_price']
df[parametros].mean().round(2)

track_price         1.20
collection_price    8.66
dtype: float64

In [26]:
# Existe variação de preço dependendo do gênero? Construa uma tabela mostrando o track_price máximo, mínimo e médio por gênero.
df.groupby('genre').agg(
    máximo = ('track_price', 'max'),
    mínimo = ('track_price', 'min'),
    médio = ('track_price', 'mean')
    )

                     máximo  mínimo     médio
genre
African                0.99    0.99  0.990000
Afro-Beat              1.29    0.99  1.190000
Afro-Pop               1.29    0.99  1.190000
Afro-fusion            1.29    1.29  1.290000
Afrobeats              1.29    0.69  1.156667
...                     ...     ...       ...
Traditional Country    1.29    1.29  1.290000
Urbano latino          1.29    1.29  1.290000
Vocal                  1.29    1.29  1.290000
Vocal Pop              1.29    1.29  1.290000
Worldwide              1.29    0.69  0.955000

[97 rows x 3 columns]

In [27]:
# Quais são os 10 artistas com o maior número de faixas no dataset?
top_10_artist = df['artist_name'].value_counts().head(10).index

In [28]:
# Desses 10 artistas, qual possui a maior média de track_price?
df[df['artist_name'].isin(top_10_artist)].groupby('artist_name')['track_price'].mean().round(2)

artist_name
Beyoncé            1.26
Diljit Dosanjh     1.11
Ed Sheeran         1.29
Eminem             1.26
Justin Bieber      1.29
Michael Jackson    1.29
Rihanna            1.26
Taylor Swift       1.28
The Beatles        1.29
The Weeknd         1.29
Name: track_price, dtype: float64

In [29]:
# A duração das músicas está diminuindo com o passar dos anos? Agrupe os dados por release_year e calcule a média de track_time_minutes.
# (Dica de BI: filtre apenas os anos que possuem mais de 20 músicas lançadas para evitar distorções estatísticas de anos muito antigos).
contagem_anos = df['release_year'].value_counts()

filtros_anos = contagem_anos[contagem_anos > 20].index

df[df['release_year'].isin(filtros_anos)].groupby('release_year')['track_time_minutes'].mean().round(2)

release_year
1965    3.57
1967    4.10
1968    4.29
1969    3.78
1973    4.53
1975    5.10
1977    4.80
1978    4.51
1980    4.96
1981    4.83
1982    4.71
1987    4.51
1991    4.61
1994    4.28
1995    4.95
1996    4.65
1997    4.36
1998    6.12
1999    4.20
2000    4.67
2001    4.92
2002    4.73
2003    4.47
2004    5.13
2005    4.22
2006    4.47
2007    4.23
2008    4.04
2009    4.20
2010    4.26
2011    4.30
2012    4.08
2013    4.44
2014    4.17
2015    3.98
2016    3.70
2017    4.12
2018    3.61
2019    3.70
2020    4.09
2021    3.68
2022    3.48
2023    3.41
2024    3.32
2025    3.38
2026    3.75
Name: track_time_minutes, dtype: float64

In [30]:
# A gravadora quer saber se vale a pena vender o álbum fechado ou apenas singles.
df_album = df.groupby('collection_name').agg(
    qtd_faixas = ('track_id', 'count'),
    preco_album = ('collection_price', 'mean'),
    soma_musica = ('track_price', 'sum'),
    track_price = ('track_price', 'mean')
)

# Filtra álbuns a partir de 5 músicas
df_album = df_album[df_album['qtd_faixas'] >= 5]

# Cria uma coluna para saber o desconto entre o álbum e a soma das músicas individuais do álbum
df_album['desconto_oferecido'] = df_album['soma_musica'] - df_album['preco_album']

# Exibi os 5 álbuns com o melhor desconto
df_album.sort_values(by='desconto_oferecido', ascending=False).head().round(2)

,qtd_faixas,preco_album,soma_musica,track_price,desconto_oferecido
collection_name,,,,,
Top Hits 2024,45,9.70,57.90,1.29,48.20
Old Hindi Songs,30,9.09,38.40,1.28,29.31
Shoot For The Stars Aim For The Moon (Deluxe),33,15.99,42.57,1.29,26.58
Focus - Single,22,2.24,26.88,1.22,24.64
Country Top Hits 2024,26,9.99,33.54,1.29,23.55

In [31]:
# Descubra o número de faixas por álbum (collection_name) presentes no dataset.
df.groupby('collection_name')['track_id'].count().sort_values(ascending=False)

collection_name
Top Hits 2024                                                                                                              45
Shoot For The Stars Aim For The Moon (Deluxe)                                                                              33
Old Hindi Songs                                                                                                            30
Country Top Hits 2024                                                                                                      26
Moosetape                                                                                                                  26
                                                                                                                           ..
His Story                                                                                                                   1
History of Indian Film Music, [Bedard Zamana Kya Jane (1959), Boot Polish (1953), Chalti Ka Naam Gaadi (1958)], Vol. 18     1
Hitotsubu No Umi                                                                                                            1
Hits 2023 (Mashup) - Single                                                                                                 1
우중간 밀어치기 - EP                                                                                                               1
Name: track_id, Length: 2801, dtype: int64

In [32]:
# Para os álbuns que têm pelo menos 5 faixas neste dataset, calcule a métrica de "Custo por Faixa no Álbum" (collection_price / quantidade de faixas).
# Compare isso com o track_price médio do mesmo álbum. O iTunes dá desconto para quem compra o álbum completo?
df_album['Custo por Faixa no Álbum'] = df_album['preco_album'] / df_album['qtd_faixas']
df_album['Desconto Álbum por Faixa'] = df_album['Custo por Faixa no Álbum'] - df_album['track_price']

df_album.sort_values(by='Desconto Álbum por Faixa', ascending=True).head().round(2)

,qtd_faixas,preco_album,soma_musica,track_price,desconto_oferecido,Custo por Faixa no Álbum,Desconto Álbum por Faixa
collection_name,,,,,,,
Party Songs Neha Kakkar,6,-1.00,5.94,0.99,6.94,-0.17,-1.16
Focus - Single,22,2.24,26.88,1.22,24.64,0.10,-1.12
Love Songs - Single,9,1.22,11.01,1.22,9.79,0.14,-1.09
Top Hits 2024,45,9.70,57.90,1.29,48.20,0.22,-1.07
Party - Single,16,2.34,19.14,1.20,16.80,0.15,-1.05

In [33]:
df.to_csv(r'..\dados_pbi\itunes_music_dataset_pbi.csv', sep=',')

In [34]:
# Agora que você extraiu todas essas informações, você precisa montar uma apresentação (pode ser um dashboard no Power BI/Tableau ou uma apresentação em Slides/Markdown baseada nos seus gráficos do Python).

# Estruture seu case com os seguintes slides/seções:

# Visão Geral do Mercado: Um resumo sobre o volume de faixas e os gêneros que dominam o iTunes.

# Estratégia de Precificação: Qual o preço ideal sugerido para lançar um single de Pop vs um single de Rock, baseado nos dados do mercado?

# Estratégia de Produto (Duração): Qual a meta de tempo (em minutos) que a área de produção da gravadora deve focar ao gravar novas músicas para maximizar a aceitação (baseando-se na tendência dos últimos anos)?

# Recomendação Final: A NovaWave Records deve focar em lançar artistas focados em singles avulsos ou produzir álbuns completos com desconto? Baseie sua resposta nos dados levantados no exercício 8.